In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/rashakil-ds/Public-Datasets/main/automobile.csv'
df = pd.read_csv(url)

C:\Users\USER\AppData\Local\Temp\ipykernel_7552\310518557.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [3]:
cols = df.columns

In [4]:
cols

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

# Goal & Steps:

1. Predicting Car Prices:
   - Task: Build a regression model to predict the price of cars based on other features in the dataset. This could involve preprocessing the data, selecting relevant features, and implementing regression algorithms.

2. Feature Engineering:
   - Task: Challenge students to come up with creative ways to engineer new features from the existing ones. For example, they could create a new feature representing the ratio of horsepower to curb weight.

3. Exploratory Data Analysis (EDA):
   - Task: Have students perform in-depth exploratory data analysis to understand the relationships between different features. Visualization tools can be used to communicate their findings effectively.

4. Handling Missing Data:
   - Task: Teach students how to handle missing data in a dataset. They can explore different strategies such as imputation or removal of missing values.

5. Hyperparameter Tuning:
   - Task: If students are using machine learning models with hyperparameters, they can explore techniques for hyperparameter tuning to optimize the performance of their models.

6. Model evaluation:
- Summarizing their findings. This should include a clear explanation of the model's performance and any insights gained from the analysis.

In [5]:
df.sample(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
24,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6692
183,2,94.0,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.4,23.0,68,4500,37,42,9495
82,1,125.0,mitsubishi,gas,std,four,sedan,fwd,front,96.3,...,122,2bbl,3.35,3.46,8.5,88,5000,25,32,6989
195,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
150,0,81.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62,4800,27,32,7898
14,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
36,0,106.0,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.0,86,5800,27,33,7895
119,1,154.0,plymouth,gas,std,four,sedan,fwd,front,93.7,...,98,2bbl,2.97,3.23,9.4,68,5500,31,38,7609

In [6]:
df.shape

(202, 26)

In [7]:
df.isnull().sum()

symboling             0
normalized-losses    37
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  0
stroke                0
compression-ratio     0
horsepower            0
peak-rpm              0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [8]:
missing_values = ['?', 'NA', 'na', 'N/A', 'n/a', 'NULL', 'null', '']
df.replace(missing_values, float('NaN'), inplace=True)

In [9]:
df.isnull().sum()

symboling             0
normalized-losses    37
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [10]:
df[['normalized-losses', 'num-of-doors','bore','stroke','horsepower','peak-rpm']].sample(10)

     normalized-losses num-of-doors  bore stroke horsepower peak-rpm
165              134.0          two  3.62    3.5        116     4800
177                NaN         four  3.27   3.35        156     5200
66                93.0          two  3.58   3.64        123     4350
70                 NaN         four   3.8   3.35        184     4500
5                  NaN          two  3.19    3.4        110     5500
45                 NaN         four  3.63   4.17        176     4750
173               65.0         four  3.31   3.54         92     4200
56               129.0          two  3.39   3.39         84     4800
12               188.0         four  3.31   3.19        121     4250
166              134.0          two  3.62    3.5        116     4800

In [11]:
df.duplicated().sum()

1

In [12]:
df.shape

(202, 26)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(201, 26)

In [15]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

#### Fill missing value ['normalized-losses', 'num-of-doors','bore','stroke','horsepower','peak-rpm']

In [16]:
df['bore'] = df['bore'].astype(float)
df['stroke'] = df['stroke'].astype(float)

In [17]:
df['horsepower'] = df['horsepower'].astype(float)
df['peak-rpm'] = df['peak-rpm'].astype(float)

In [18]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450

In [19]:
df.sample(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
137,0,102.0,subaru,gas,std,four,sedan,fwd,front,97.2,...,108,2bbl,3.62,2.64,9.5,82.0,4800.0,32,37,7126
95,2,168.0,nissan,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.4,69.0,5200.0,31,37,8249
81,3,NaN,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,14489
32,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.2,76.0,6000.0,30,34,6529
141,0,102.0,subaru,gas,turbo,four,sedan,4wd,front,97.0,...,108,mpfi,3.62,2.64,7.7,111.0,4800.0,24,29,11259
148,1,74.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6488
75,2,161.0,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.4,68.0,5500.0,31,38,6669
103,1,231.0,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160.0,5200.0,19,25,18399
179,2,122.0,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85.0,5250.0,27,34,7975
121,3,NaN,plymouth,gas,turbo,two,hatchback,rwd,front,95.9,...,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,12764

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       199 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               197 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    float64
 22  peak-rpm           199 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    int64
dtypes: float64(10), int64(6), object(10)
memory usage: 42.4+ KB

In [21]:
df['num-of-doors'].mode()

0    four
Name: num-of-doors, dtype: object

In [22]:
df['num-of-doors'].fillna('four', inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_7552\3474437114.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['num-of-doors'].fillna('four', inplace=True)

In [23]:
df['normalized-losses'].fillna(df['normalized-losses'].median(), inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_7552\1935756503.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['normalized-losses'].fillna(df['normalized-losses'].median(), inplace=True)

In [24]:
df['bore'].fillna(df['bore'].mean(), inplace=True)
df['stroke'].fillna(df['stroke'].mean(), inplace=True)
df['horsepower'].fillna(df['horsepower'].mean(), inplace=True)
df['peak-rpm'].fillna(df['peak-rpm'].mean(), inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_7552\1389755688.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bore'].fillna(df['bore'].mean(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_7552\1389755688.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['stroke'].fillna(df['stroke'].mean(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_7552\1389755688.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].mean(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_7552\1389755688.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['peak-rpm'].fillna(df['peak-rpm'].mean(), inplace=True)

In [25]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,115.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495
1,3,115.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
2,1,115.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    float64
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         201 non-null    float64
 22  peak-rpm           201 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    int64
dtypes: float64(10), int64(6), object(10)
memory usage: 42.4+ KB

In [27]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

# Encoding

In [28]:
nums = []
for i in df.columns:
    if df[i].dtypes != 'object':
        nums.append(i)

In [29]:
nums

['symboling',
 'normalized-losses',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-size',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg',
 'price']

In [30]:
num_col = ['symboling',
 'normalized-losses',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-size',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg']

In [31]:
cats = []
for i in df.columns:
    if df[i].dtypes == 'object':
        cats.append(i)

In [32]:
cats

['make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 'engine-type',
 'num-of-cylinders',
 'fuel-system']

In [33]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [34]:
ss = StandardScaler()

In [35]:
df[num_col]=ss.fit_transform(df[num_col])

In [36]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,1.725050,-0.178306,alfa-romero,gas,std,two,convertible,rwd,front,-1.685107,...,0.075389,mpfi,0.520894,-1.829927,-0.291435,0.203984,-0.246556,-0.652249,-0.542288,13495
1,1.725050,-0.178306,alfa-romero,gas,std,two,convertible,rwd,front,-1.685107,...,0.075389,mpfi,0.520894,-1.829927,-0.291435,0.203984,-0.246556,-0.652249,-0.542288,16500
2,0.127193,-0.178306,alfa-romero,gas,std,two,hatchback,rwd,front,-0.710103,...,0.606234,mpfi,-2.433435,0.675938,-0.291435,1.357649,-0.246556,-0.964397,-0.689386,16500
3,0.926121,1.351431,audi,gas,std,four,sedan,fwd,front,0.165748,...,-0.431327,mpfi,-0.526210,0.453899,-0.041121,-0.037480,0.801833,-0.184027,-0.100993,13950
4,0.926121,1.351431,audi,gas,std,four,sedan,4wd,front,0.099646,...,0.220165,mpfi,-0.526210,0.453899,-0.541748,0.311302,0.801833,-1.120471,-1.277779,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1.470664,-0.802689,volvo,gas,std,four,sedan,rwd,front,1.702619,...,0.340812,mpfi,1.680188,-0.339096,-0.166278,0.284473,0.592155,-0.340101,-0.395189,16845
197,-1.470664,-0.802689,volvo,gas,turbo,four,sedan,rwd,front,1.702619,...,0.340812,mpfi,1.680188,-0.339096,-0.366529,1.518625,0.382477,-0.964397,-0.836484,19045
198,-1.470664,-0.802689,volvo,gas,std,four,sedan,rwd,front,1.702619,...,1.112950,mpfi,0.932257,-1.227251,-0.341497,0.821061,0.801833,-1.120471,-1.130681,21485
199,-1.470664,-0.802689,volvo,diesel,turbo,four,sedan,rwd,front,1.702619,...,0.437329,idi,-1.199348,0.453899,3.212954,0.069837,-0.665911,0.128120,-0.542288,22470
200,-1.470664,-0.802689,volvo,gas,turbo,four,sedan,rwd,front,1.702619,...,0.340812,mpfi,1.680188,-0.339096,-0.166278,0.284473,0.592155,-0.964397,-0.836484,22625

In [37]:
le = LabelEncoder()

for i in cats:
    df[i] = le.fit_transform(df[i])

In [38]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,1.725050,-0.178306,0,1,0,1,0,2,0,-1.685107,...,0.075389,5,0.520894,-1.829927,-0.291435,0.203984,-0.246556,-0.652249,-0.542288,13495
1,1.725050,-0.178306,0,1,0,1,0,2,0,-1.685107,...,0.075389,5,0.520894,-1.829927,-0.291435,0.203984,-0.246556,-0.652249,-0.542288,16500
2,0.127193,-0.178306,0,1,0,1,2,2,0,-0.710103,...,0.606234,5,-2.433435,0.675938,-0.291435,1.357649,-0.246556,-0.964397,-0.689386,16500
3,0.926121,1.351431,1,1,0,0,3,1,0,0.165748,...,-0.431327,5,-0.526210,0.453899,-0.041121,-0.037480,0.801833,-0.184027,-0.100993,13950
4,0.926121,1.351431,1,1,0,0,3,0,0,0.099646,...,0.220165,5,-0.526210,0.453899,-0.541748,0.311302,0.801833,-1.120471,-1.277779,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1.470664,-0.802689,21,1,0,0,3,2,0,1.702619,...,0.340812,5,1.680188,-0.339096,-0.166278,0.284473,0.592155,-0.340101,-0.395189,16845
197,-1.470664,-0.802689,21,1,1,0,3,2,0,1.702619,...,0.340812,5,1.680188,-0.339096,-0.366529,1.518625,0.382477,-0.964397,-0.836484,19045
198,-1.470664,-0.802689,21,1,0,0,3,2,0,1.702619,...,1.112950,5,0.932257,-1.227251,-0.341497,0.821061,0.801833,-1.120471,-1.130681,21485
199,-1.470664,-0.802689,21,0,1,0,3,2,0,1.702619,...,0.437329,3,-1.199348,0.453899,3.212954,0.069837,-0.665911,0.128120,-0.542288,22470
200,-1.470664,-0.802689,21,1,1,0,3,2,0,1.702619,...,0.340812,5,1.680188,-0.339096,-0.166278,0.284473,0.592155,-0.964397,-0.836484,22625

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    float64
 1   normalized-losses  201 non-null    float64
 2   make               201 non-null    int32
 3   fuel-type          201 non-null    int32
 4   aspiration         201 non-null    int32
 5   num-of-doors       201 non-null    int32
 6   body-style         201 non-null    int32
 7   drive-wheels       201 non-null    int32
 8   engine-location    201 non-null    int32
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    float64
 14  engine-type        201 non-null    int32
 15  num-of-cylinders   201 non-null    int32
 16  engine-size        201 non-null    float64
 17  fuel-system        201 non-null    int32
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         201 non-null    float64
 22  peak-rpm           201 non-null    float64
 23  city-mpg           201 non-null    float64
 24  highway-mpg        201 non-null    float64
 25  price              201 non-null    int64
dtypes: float64(15), int32(10), int64(1)
memory usage: 34.5 KB

In [40]:
df.sample(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
130,1.725050,0.914363,17,1,0,1,2,1,0,0.050070,...,-0.141775,5,-2.956987,-3.764836,-0.216341,0.177155,0.277639,-0.652249,-0.395189,15040
82,0.127193,0.133885,11,1,0,0,3,1,0,-0.412644,...,-0.117645,1,0.072136,0.644218,-0.416591,-0.413092,-0.246556,-0.027954,0.193204,6989
14,-0.671736,-0.178306,2,1,0,0,3,2,0,0.777192,...,1.981605,5,1.081843,0.422179,-0.541748,2.108872,0.592155,-1.432618,-1.277779,30760
123,1.725050,-0.178306,15,1,0,1,1,2,1,-1.536378,...,1.619666,5,1.530602,-1.132091,-0.166278,2.779607,1.640544,-1.276544,-0.836484,32528
80,1.725050,-0.178306,11,1,1,1,2,1,0,-0.478746,...,0.702751,6,0.969653,1.913011,-0.792062,1.116184,-0.246556,-0.964397,-0.983583,14869
7,0.127193,-0.178306,1,1,0,0,4,1,0,1.157278,...,0.220165,5,-0.526210,0.453899,-0.416591,0.177155,0.801833,-0.964397,-0.836484,18920
139,-0.671736,-0.584155,18,1,0,0,3,1,0,-0.263915,...,-0.455456,5,1.081843,-1.956806,-0.291435,-0.252116,0.172800,0.128120,0.193204,9960
133,0.926121,-0.521717,17,1,1,0,3,1,0,0.050070,...,-0.141775,5,0.782671,-0.592855,-0.291435,1.518625,0.801833,-0.964397,-0.689386,18620
198,-1.470664,-0.802689,21,1,0,0,3,2,0,1.702619,...,1.112950,5,0.932257,-1.227251,-0.341497,0.821061,0.801833,-1.120471,-1.130681,21485
87,0.127193,0.227542,12,0,0,1,3,1,0,-0.710103,...,-0.576103,3,-1.274141,0.675938,2.937609,-1.298462,-0.665911,3.093524,2.840973,7099

In [41]:
df.corr().transpose()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
symboling,1.000000,0.457735,-0.129645,0.196735,-0.054615,0.672344,-0.600333,-0.053056,0.212339,-0.535987,...,-0.110581,0.091601,-0.139896,-0.007992,-0.182196,0.075790,0.279719,-0.035527,0.036233,-0.082391
normalized-losses,0.457735,1.000000,-0.237573,0.105970,-0.010780,0.355303,-0.246047,0.291007,-0.021948,-0.075109,...,0.073586,0.198932,-0.050688,0.044119,-0.115967,0.182125,0.246242,-0.193896,-0.150773,0.094366
make,-0.129645,-0.237573,1.000000,-0.109330,0.071254,-0.146172,0.090621,-0.034844,0.053312,0.073930,...,-0.084770,0.144769,0.236765,-0.203756,0.132554,-0.064598,-0.213009,0.065761,0.059111,-0.163646
fuel-type,0.196735,0.105970,-0.109330,1.000000,-0.408228,0.186681,-0.147654,-0.131096,0.040917,-0.307237,...,-0.070779,0.042824,-0.054435,-0.241033,-0.985231,0.168977,0.475759,-0.265676,-0.198690,-0.110326
aspiration,-0.054615,-0.010780,0.071254,-0.408228,1.000000,-0.063017,0.072079,0.094469,-0.057496,0.256889,...,0.110040,0.282269,0.227782,0.218190,0.307522,0.251235,-0.189982,-0.189237,-0.241851,0.179578
num-of-doors,0.672344,0.355303,-0.146172,0.186681,-0.063017,1.000000,-0.688542,0.115920,0.142340,-0.445245,...,-0.024094,-0.001246,-0.119140,0.007780,-0.169164,0.102856,0.232031,0.027617,0.045787,-0.042435
body-style,-0.600333,-0.246047,0.090621,-0.147654,0.072079,-0.688542,1.000000,-0.161004,-0.278350,0.407128,...,-0.063692,-0.054810,0.021182,-0.013468,0.134622,-0.136575,-0.105785,0.014217,-0.021328,-0.072933
drive-wheels,-0.053056,0.291007,-0.034844,-0.131096,0.094469,0.115920,-0.161004,1.000000,0.149369,0.467661,...,0.526027,0.435926,0.471925,0.078852,0.120125,0.546033,-0.035667,-0.469240,-0.472893,0.588333
engine-location,0.212339,-0.021948,0.053312,0.040917,-0.057496,0.142340,-0.278350,0.149369,1.000000,-0.189115,...,0.199367,0.106735,0.188404,-0.139351,-0.020467,0.342146,0.201937,-0.157132,-0.102964,0.331062
wheel-base,-0.535987,-0.075109,0.073930,-0.307237,0.256889,-0.445245,0.407128,0.467661,-0.189115,1.000000,...,0.572027,0.381273,0.493203,0.157964,0.250313,0.371250,-0.360233,-0.470606,-0.543304,0.584642
length,-0.365404,-0.009116,0.110468,-0.211187,0.230085,-0.395122,0.347571,0.495197,-0.053086,0.876024,...,0.685025,0.551120,0.608941,0.123913,0.159733,0.579731,-0.286035,-0.665192,-0.698142,0.690628
width,-0.242423,0.061799,-0.005115,-0.244356,0.305732,-0.227655,0.155366,0.481395,-0.052205,0.814507,...,0.729436,0.513371,0.544879,0.188814,0.189867,0.615006,-0.245852,-0.633531,-0.680635,0.751265
height,-0.550160,-0.371830,0.230754,-0.281578,0.090336,-0.538383,0.571107,-0.025096,-0.109225,0.590742,...,0.074694,0.018196,0.180327,-0.060822,0.259737,-0.086941,-0.309913,-0.049800,-0.104812,0.135486
curb-weight,-0.233118,0.065393,0.017115,-0.221046,0.321955,-0.208517,0.145762,0.590642,0.051287,0.782097,...,0.849072,0.602638,0.644041,0.167412,0.156433,0.757994,-0.279350,-0.749543,-0.794889,0.834415
engine-type,0.091801,-0.054761,-0.044549,0.124051,-0.130898,0.109089,-0.080350,-0.067339,0.125683,-0.143928,...,0.118248,-0.042551,0.078992,-0.167827,-0.105280,0.144453,0.057607,-0.171524,-0.156458,0.126025
num-of-cylinders,0.199377,0.171445,-0.049947,0.120638,-0.129771,0.185434,-0.063741,0.231177,0.136009,-0.190489,...,-0.064607,0.028508,-0.010397,-0.054505,-0.072699,0.201941,0.253987,-0.157424,-0.101386,0.005509
engine-size,-0.110581,0.073586,-0.084770,-0.070779,0.110040,-0.024094,-0.063692,0.526027,0.199367,0.572027,...,1.000000,0.507264,0.572516,0.205806,0.028889,0.822649,-0.256753,-0.650546,-0.679571,0.872335
fuel-system,0.091601,0.198932,0.144769,0.042824,0.282269,-0.001246,-0.054810,0.435926,0.106735,0.381273,...,0.507264,1.000000,0.470961,0.084040,-0.099933,0.672869,0.012238,-0.663651,-0.638017,0.521689
bore,-0.139896,-0.050688,0.236765,-0.054435,0.227782,-0.119140,0.021182,0.471925,0.188404,0.493203,...,0.572516,0.470961,1.000000,-0.055390,0.001250,0.566838,-0.267338,-0.582121,-0.591390,0.543154
stroke,-0.007992,0.044119,-0.203756,-0.241033,0.218190,0.007780,-0.013468,0.078852,-0.139351,0.157964,...,0.205806,0.084040,-0.055390,1.000000,0.187854,0.097815,-0.063720,-0.034079,-0.034741,0.082267
compression-ratio,-0.182196,-0.115967,0.132554,-0.985231,0.307522,-0.169164,0.134622,0.120125,-0.020467,0.250313,...,0.028889,-0.099933,0.001250,0.187854,1.000000,-0.214431,-0.435721,0.331425,0.268465,0.071107
horsepower,0.075790,0.182125,-0.064598,0.168977,0.251235,0.102856,-0.136575,0.546033,0.342146,0.371250,...,0.822649,0.672869,0.566838,0.097815,-0.214431,1.000000,0.107882,-0.822138,-0.804587,0.809681
peak-rpm,0.279719,0.246242,-0.213009,0.475759,-0.189982,0.232031,-0.105785,-0.035667,0.201937,-0.360233,...,-0.256753,0.012238,-0.267338,-0.063720,-0.435721,0.107882,1.000000,-0.115358,-0.058605,-0.101542
city-mpg,-0.035527,-0.193896,0.065761,-0.265676,-0.189237,0.027617,0.014217,-0.469240,-0.157132,-0.470606,...,-0.650546,-0.663651,-0.582121,-0.034079,0.331425,-0.822138,-0.115358,1.000000,0.972044,-0.686571
highway-mpg,0.036233,-0.150773,0.059111,-0.198690,-0.241851,0.045787,-0.021328,-0.472893,-0.102964,-0.543304,...,-0.679571,-0.638017,-0.591390,-0.034741,0.268465,-0.804587,-0.058605,0.972044,1.000000,-0.704692
price,-0.082391,0.094366,-0.163646,-0.110326,0.179578,-0.042435,-0.072933,0.588333,0.331062,0.584642,...,0.872335,0.521689,0.543154,0.082267,0.071107,0.809681,-0.101542,-0.686571,-0.704692,1.000000

# Train-Test Split

In [42]:
X = df.drop('price', axis = 1)
y = df['price']

In [43]:
X.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,1.725050,-0.178306,0,1,0,1,0,2,0,-1.685107,...,2,0.075389,5,0.520894,-1.829927,-0.291435,0.203984,-0.246556,-0.652249,-0.542288
1,1.725050,-0.178306,0,1,0,1,0,2,0,-1.685107,...,2,0.075389,5,0.520894,-1.829927,-0.291435,0.203984,-0.246556,-0.652249,-0.542288
2,0.127193,-0.178306,0,1,0,1,2,2,0,-0.710103,...,3,0.606234,5,-2.433435,0.675938,-0.291435,1.357649,-0.246556,-0.964397,-0.689386
3,0.926121,1.351431,1,1,0,0,3,1,0,0.165748,...,2,-0.431327,5,-0.526210,0.453899,-0.041121,-0.037480,0.801833,-0.184027,-0.100993
4,0.926121,1.351431,1,1,0,0,3,0,0,0.099646,...,1,0.220165,5,-0.526210,0.453899,-0.541748,0.311302,0.801833,-1.120471,-1.277779

In [44]:
y.head()

0    13495
1    16500
2    16500
3    13950
4    17450
Name: price, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
X_train.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
198,-1.470664,-0.802689,21,1,0,0,3,2,0,1.702619,...,3,1.112950,5,0.932257,-1.227251,-0.341497,0.821061,0.801833,-1.120471,-1.130681
38,-0.671736,-1.114880,5,1,0,0,3,1,0,-0.379593,...,2,-0.407197,0,-0.675796,1.024856,-0.291435,-0.466751,1.430866,0.284194,0.340302
24,0.127193,0.851925,4,1,0,0,3,1,0,-0.842307,...,2,-0.889784,1,-1.348934,-0.085338,-0.191309,-0.949680,0.801833,0.908490,1.075793
122,1.725050,2.038252,15,1,0,1,2,2,0,-0.710103,...,2,0.582105,5,2.278534,-0.465975,-0.166278,1.062525,0.801833,-0.964397,-0.542288
196,-1.470664,-0.802689,21,1,0,0,3,2,0,1.702619,...,2,0.340812,5,1.680188,-0.339096,-0.166278,0.284473,0.592155,-0.340101,-0.395189

# Linear Regression

In [48]:
from sklearn.linear_model import LinearRegression

In [49]:
lr = LinearRegression()

In [50]:
lr.fit(X_train, y_train)

LinearRegression()

In [51]:
y_pred = lr.predict(X_test)

In [52]:
y_pred

array([ 8103.16786117, 23389.90059544,  6171.36281212,  6240.65638176,
       13352.51222179,  5174.02285626, 29218.66375095, 10436.58091056,
       18762.9658907 , 28248.65362161, 23742.37567231,  9965.11671771,
       13291.66960765,  9213.38549419, 13215.66340525,  7043.10543077,
       10811.81953234,  6197.34116505,  9468.33531229, 31486.83919344,
       32528.        , 27986.22200893,  6880.46031334,  7360.96156618,
       23624.51910389, 12032.90378355, 11356.1407894 , 25504.37054006,
       33437.23245533, 14917.01438748, 14274.14040359,  7446.2802739 ,
       11272.98330382,  6996.05521769,  4692.42479251, 15964.81522352,
        7497.53332067,  9033.27798221, 14172.58708439,  8554.45076327,
       14368.25649267])

In [53]:
y_test

95      8249
15     41315
30      6855
158     9258
128    11850
115     5572
69     35056
171     9988
175    15998
45     35550
66     28176
183     9495
165     9989
78      8499
187    13295
178     7775
56      8845
152     6938
82      6989
68     34184
124    34028
16     36880
148     6488
93      7499
65     28248
60     10795
84      9279
67     31600
125    37028
132    18150
9      16430
18      6295
55     15645
75      6669
150     7898
104    11900
135     7053
137     7126
164     9639
76      7689
79     12629
Name: price, dtype: int64

### Accuracy

In [54]:
test_acc = lr.score(X_test,y_test)

In [55]:
test_acc

0.8549446025084557

In [56]:
train_acc = lr.score(X_train,y_train)

In [57]:
train_acc

0.8924935969515001

In [58]:
from sklearn.metrics import r2_score

In [59]:
score = r2_score(y_test, y_pred)

In [60]:
score

0.8549446025084557